steps:
  # Step 1: Uses the default pipeline repo (no plugin needed)
  - label: "Step 1: Pipeline repo"
    command: |
      echo "This step checked out the pipeline repo"
      echo "Current directory: $(pwd)"

  # Step 3: SonarCloud Analysis
  - label: "🔍 SonarCloud Analysis"
    command: |
      # Install sonar-scanner if not available
      if ! command -v sonar-scanner &> /dev/null; then
        echo "Installing SonarQube Scanner (Java 11 compatible)..."
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip -q sonar-scanner-cli.zip
        export PATH="$(pwd)/sonar-scanner-4.7.0.2747-linux/bin:$PATH"
      fi
      
      # Run SonarQube analysis
      sonar-scanner
    env:
      SONAR_HOST_URL: "https://sonarcloud.io"
    plugins:
      - seek-oss/aws-sm#v2.3.3:
          env:
            SONAR_TOKEN: ola/sonar-token

