steps:
  # Step 1: Uses the default pipeline repo (no plugin needed)
  - label: "Step 1: Pipeline repo"
    command: |
      echo "This step checked out the pipeline repo"
      echo "Current directory: $(pwd)"

  # Step 3: SonarCloud Analysis
  - label: "🔍 SonarCloud Analysis"
    plugins:
      - seek-oss/aws-sm#v2.3.3:
          env:
            SONAR_TOKEN: ola/sonar-token
      - docker#v5.11.0:
          image: "sonarsource/sonar-scanner-cli:latest"
          environment:
            - "SONAR_HOST_URL=https://sonarcloud.io"
            - "SONAR_TOKEN=$$SONAR_TOKEN"

