agents:
  queue: "mac"
steps:
  # Step 1: Uses the default pipeline repo (no plugin needed)
  - label: "Step 1: Pipeline repo"
    command: |
      echo "This step checked out the pipeline repo"
      echo "Current directory: $(pwd)"

  # Step 2: Uses the plugin to checkout your k8s-test repo
  - label: "Step 2: k8s-test repo"
    command: |
      echo "This step checked out the k8s-test repo"
      echo "Current directory: $(pwd)"
      
    plugins:
      - git-ssh-checkout#v0.4.1:
          repository-url: "git@github.com:Mykematt/k8s-test.git"
          ssh-secret-key-name: "GIT_SSH_CHECKOUT_PLUGIN_SSH_KEY"
          checkout-path: ./k8s-test  # Different path!

